# Generated by Django 4.1.6 on 2023-02-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("android_version", models.CharField(blank=True, max_length=20)),
                ("ios_version", models.CharField(blank=True, max_length=20)),
                (
                    "android_dismissible",
                    models.BooleanField(blank=True, default=False, max_length=20),
                ),
                (
                    "ios_dismissible",
                    models.BooleanField(blank=True, default=False, max_length=20),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
